# Generated by Django 6.0.7 on 2026-07-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurantreview_ordered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='hash_id',
            field=models.CharField(db_index=True, default='', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantreview',
            name='hash_id',
            field=models.CharField(db_index=True, default='', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
