# Generated by Django 6.0.7 on 2026-07-20 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurant_hash_id_restaurantreview_hash_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='hash_id',
        ),
        migrations.RemoveField(
            model_name='restaurantreview',
            name='hash_id',
        ),
    ]
