# Generated by Django 6.0.7 on 2026-07-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_remove_restaurant_hash_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
