# Generated by Django 6.0.7 on 2026-07-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_restaurantreview_menu_alter_restaurant_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantreview',
            name='menu',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
