# Generated by Django 6.0.7 on 2026-08-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_restaurantreview_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantreview',
            name='content',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
