# Generated by Django 6.0.7 on 2026-07-20 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0002_zone_hash_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='hash_id',
        ),
    ]
