"""
Django settings for meokbogi_api project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# 이 파일은 개발·테스트용 기본값이다. 운영 설정은 settings/product.py 를 쓴다.
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# 운영에서는 반드시 환경변수로 주입한다. product.py 는 값이 없으면 부팅에 실패한다.
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-dev-only-do-not-deploy")

DEBUG = os.environ.get("DJANGO_DEBUG", "true").lower() == "true"

ALLOWED_HOSTS = ["localhost"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "rest_framework",
    # 로그아웃·토큰 회전 시 이전 refresh 토큰을 무효화한다 (만료된 기록은 flushexpiredtokens로 정리)
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",  # CORS 처리 시 필요 (프론트엔드 분리 시 권장)

    "apps.zone",
    "apps.restaurant",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'meokbogi_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'meokbogi_api.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

# 사용자가 한국 기준이므로 "이번 달" 같은 날짜 경계도 KST로 잡는다
TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
APPEND_SLASH = False
REST_FRAMEWORK = {
    # 인증 방식 (여러 개 설정 가능, 위에서부터 순서대로 시도)
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication",
        # JWT 사용 시 (djangorestframework-simplejwt 설치 필요):
    ],

    # 기본 권한 클래스
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],

    # 페이지네이션
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,

    # 필터링 / 검색 / 정렬 백엔드
    "DEFAULT_FILTER_BACKENDS": [
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],

    # 응답 포맷 (렌더러)
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        # 개발 중에는 브라우저블 API도 유용함 (배포 시 제거 고려)
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],

    # 요청 파서
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ],

    # 요청 제한 (Throttling) - 필요 시 활성화
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    # 앱을 열 때마다 refresh-token(익명)이 한 번씩 나가므로 anon을 일 단위로 묶으면
    # 같은 공유기 뒤 사용자 몇 명만으로도 자동로그인이 429로 막힌다. 분 단위로 잡고,
    # 무차별 대입은 로그인 전용 scope(login)로 따로 막는다.
    "DEFAULT_THROTTLE_RATES": {
        "anon": "60/min",
        "user": "120/min",
        "login": "10/min",
    },

    # 날짜/시간 포맷
    "DATETIME_FORMAT": "%Y-%m-%d %H:%M:%S",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=20),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=15),
    "ROTATE_REFRESH_TOKENS": True,
    # 회전된 refresh 토큰은 바로 쓸 수 없게 한다. 그렇지 않으면 유출된 예전 쿠키가 15일간 유효하다.
    "BLACKLIST_AFTER_ROTATION": True,
}

# ------------------------------------------------------------------------------
# CORS 설정 (프론트엔드가 다른 도메인/포트에서 API 호출 시)
# ------------------------------------------------------------------------------
CORS_ALLOWED_ORIGINS = [origin for origin in os.environ.get("CORS_ALLOWED_ORIGINS", "").split(",") if origin]
CORS_ALLOW_CREDENTIALS = True
# 내보내기 파일 이름을 브라우저 스크립트가 읽을 수 있게 한다 (다른 출처 응답은 기본으로 숨겨진다)
CORS_EXPOSE_HEADERS = ["Content-Disposition"]

# ------------------------------------------------------------------------------
# refresh 토큰 쿠키
# ------------------------------------------------------------------------------
# 프론트와 API가 같은 사이트(등록가능도메인이 동일)면 "Lax"로 충분하다.
# 서로 다른 사이트면 "None" + Secure(=HTTPS)가 필요하다. SameSite=None은 Secure를
# 강제하므로 평문 HTTP인 로컬에서는 브라우저가 쿠키 자체를 거부한다 → 로컬은 Lax 유지.
REFRESH_COOKIE_NAME = "refreshtoken"
REFRESH_COOKIE_SAMESITE = os.environ.get("REFRESH_COOKIE_SAMESITE", "Lax")
REFRESH_COOKIE_SECURE = os.environ.get("REFRESH_COOKIE_SECURE", "false").lower() == "true"
